### ISSUE TITLE
Broadcast

### ISSUE THREAD

**Issue by niggiover9000** [verycollective/stupidArtnet#1]
Hey there!
Thank you for the great and easy to understand project!
I am wondering, if there is a way to send ArtNet as Broadcast? When using "255.255.255.255" as a destination IP, I will get an error, "Permission denied"

Thanks in advance!

**Comment by verycollective** [comment]
I guess this would depend on the equipment you are using. Some professional equipment would block full broadcast Art-Net, you can try to broadcast into the subnet instead (eg. 2.255.255.255 for a 2.0.0.1/8 IP setup)

**Comment by verycollective** [comment]
closing. not an issue

**Comment by cpvalente** [comment]
hey! I realise I misunderstood your request assuming it was a hardware configuration issue.
Either way, fixed with #7
